/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "media",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      boxShadow: {
        card1: "2px 2px var(--text)",
        card: "4px 4px var(--text)",
        hover: "10px 10px var(--text)",
        accent: "7px 7px var(--accent)",
        primary: "7px 7px var(--primary)",
        secondary: "7px 7px var(--secondary)",
        accentHover: "10px 10px var(--accent)",
        primaryHover: "10px 10px var(--primary)",
        secondaryHover: "10px 10px var(--secondary)",
      },
      colors: {
        text: "var(--text)",
        background: "var(--background)",
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
      },
      fontFamily: {
        mono: ["Alexandria", "monospace"],
        sans: ["Alexandria", "sans-serif"],
        kablamo: ["Kablammo", "serif"],
      },
      maxWidth: {
        "1/12": "8.333333%",
        "2/12": "16.666667%",
        "3/12": "25%",
        "4/12": "33.333333%",
        "5/12": "41.666667%",
        "6/12": "50%",
        "7/12": "58.333333%",
        "8/12": "66.666667%",
        "9/12": "75%",
        "10/12": "83.333333%",
        "10/12": "91.666667%",
        "12/12": "100%",
      },
      margin: {
        30: "7.3rem",
      },
      borderWidth: {
        1: "1px",
        3: "3px",
      },
      borderColor: {
        text: "var(--text)",
        textRad: "var(--text)",
        backgroundRad: "var(--background)",
      },
      typography: ({ theme }) => ({
        defaultTheme: {
          css: {
            '--tw-prose-body': 'var(--text)',
            '--tw-prose-headings': 'var(--text)',
            '--tw-prose-lead': 'var(--text)',
            '--tw-prose-links': 'var(--text)',
            '--tw-prose-bold': 'var(--text)',
            '--tw-prose-counters': 'var(--text)',
            '--tw-prose-bullets': 'var(--text)',
            '--tw-prose-hr': 'var(--text)',
            '--tw-prose-quotes': 'var(--text)',
            '--tw-prose-quote-borders': 'var(--text)',
            '--tw-prose-captions': 'var(--text)',
            '--tw-prose-code': 'var(--text)',
            '--tw-prose-pre-code': 'var(--text)',
            '--tw-prose-pre-bg': 'var(--text)',
            '--tw-prose-th-borders': 'var(--text)',
            '--tw-prose-td-borders': 'var(--text)',
            '--tw-prose-invert-body': 'var(--text)',
            '--tw-prose-invert-headings': 'var(--background)',
            '--tw-prose-invert-lead': 'var(--text)',
            '--tw-prose-invert-links': 'var(--background)',
            '--tw-prose-invert-bold': 'var(--background)',
            '--tw-prose-invert-counters': 'var(--text)',
            '--tw-prose-invert-bullets': 'var(--text)',
            '--tw-prose-invert-hr': 'var(--text)',
            '--tw-prose-invert-quotes': 'var(--text)',
            '--tw-prose-invert-quote-borders': 'var(--text)',
            '--tw-prose-invert-captions': 'var(--text)',
            '--tw-prose-invert-code': 'var(--background)',
            '--tw-prose-invert-pre-code': 'var(--text)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--text)',
            '--tw-prose-invert-td-borders': 'var(--text)',
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
